services:
  backend:
    build: 
     context: ./backend
#     args:
#      ConnectionStrings__DefaultConnection: "Host=pg-database;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PW}"  
    environment:
      ConnectionStrings__DefaultConnection: "Host=pg-database;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PW}"
    ports:
      - "8000:8080"
    depends_on:
      - pg-database
    networks:
      - backend-network
      - frontend-network
  
  frontend:
    build: 
     context: ./frontend
    environment:
      NEXT_PUBLIC_SERVICE_URL: "http://backend:8080"
    ports:
      - "5001:3000"
    depends_on:
      - backend
    networks:
      - frontend-network

  pg-database:
    image: postgres
    restart: always
    ports:
      - "8001:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend-network
    volumes:
      - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata:

networks:
  backend-network:
   name: backend_network
  frontend-network:
   name: frontend_network
